# Generated by Django 3.2.9 on 2021-12-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.CharField(max_length=255, unique=True)),
                ('cour_id', models.CharField(max_length=255, null=True, unique=True)),
                ('completed', models.IntegerField(default=0)),
                ('progress', models.JSONField(default=dict)),
                ('doe', models.DateField(auto_now=True)),
                ('doc', models.DateField(null=True)),
            ],
        ),
    ]
