# Generated by Django 3.2.9 on 2021-11-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOverview',
            fields=[
                ('std_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('course_dtls', models.JSONField()),
                ('std_skils', models.JSONField()),
            ],
        ),
    ]
