# Generated by Django 3.2.9 on 2021-12-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='thr_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='cour_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='std_id',
            field=models.CharField(max_length=255),
        ),
    ]
