# Generated by Django 3.2.9 on 2021-11-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentoverview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentoverview',
            name='course_dtls',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='studentoverview',
            name='std_skils',
            field=models.JSONField(null=True),
        ),
    ]
