# Generated by Django 3.2.9 on 2021-11-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20211121_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentoverview',
            name='course_dtls',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='studentoverview',
            name='std_skils',
            field=models.JSONField(default=[]),
        ),
    ]
