# Generated by Django 3.2.9 on 2021-11-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_studentoverview_course_dtls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentoverview',
            name='course_dtls',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='studentoverview',
            name='std_skils',
            field=models.JSONField(default=list),
        ),
    ]
