# Generated by Django 3.2.9 on 2021-11-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20211121_2324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.DeleteModel(
            name='Quality',
        ),
    ]
