# Generated by Django 3.2.9 on 2021-12-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_students_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='doe',
            field=models.DateField(auto_now_add=True),
        ),
    ]
