# Generated by Django 3.2.9 on 2021-12-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_students_doe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='StdOverview',
        ),
    ]
