# Generated by Django 3.2.9 on 2021-12-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_rename_students_stdoverview'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdoverview',
            name='cour_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
