# Generated by Django 3.2.9 on 2021-12-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_stdoverview_cour_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=255)),
                ('completed_weeks', models.JSONField()),
                ('completed_content', models.JSONField()),
            ],
        ),
    ]
