# Generated by Django 3.2.9 on 2021-12-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed',
            name='completed_content',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='completed',
            name='completed_weeks',
            field=models.JSONField(default=list),
        ),
    ]
