# Generated by Django 3.2.9 on 2021-12-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20211219_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='assignment',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='completed',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='completed',
            name='test_score',
            field=models.JSONField(default=list),
        ),
    ]
