# Generated by Django 3.2.7 on 2021-10-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='img_content',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='content/')),
                ('text', models.CharField(max_length=1000)),
                ('Reference', models.CharField(max_length=255)),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='text_content',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=1000)),
                ('reference', models.CharField(max_length=255)),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('video', models.FileField(upload_to='videos/')),
                ('time', models.IntegerField()),
            ],
        ),
    ]
