# Generated by Django 3.2.9 on 2021-11-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('teacher_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('discriptions', models.CharField(max_length=5000, null=True)),
                ('week', models.IntegerField(default=0)),
                ('unit', models.IntegerField(default=0)),
                ('enroled', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('time', models.CharField(max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('skils', models.JSONField()),
                ('Questions', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='img_content',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='content/')),
                ('text', models.CharField(max_length=1000)),
                ('Reference', models.CharField(max_length=255)),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='text_content',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=1000)),
                ('reference', models.CharField(max_length=255)),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('video', models.FileField(upload_to='videos/')),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='weeks',
            fields=[
                ('course_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('week', models.JSONField(default=list)),
                ('content', models.JSONField(default=dict)),
            ],
        ),
    ]
