# Generated by Django 3.2.7 on 2021-10-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('techer_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('desciptions', models.CharField(max_length=5000)),
                ('week', models.IntegerField(default=0)),
                ('unit', models.IntegerField(default=0)),
                ('enroled', models.IntegerField(default=0)),
                ('time', models.CharField(max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('skils', models.CharField(max_length=255)),
            ],
        ),
    ]
