# Generated by Django 3.2.9 on 2021-11-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20211114_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='regularclass',
            fields=[
                ('class_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('teacher_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('classDiv', models.CharField(max_length=20)),
                ('students', models.ImageField(upload_to='')),
            ],
        ),
    ]
