# Generated by Django 3.2.9 on 2021-11-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_regularclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularclass',
            name='enroled',
            field=models.IntegerField(default=0),
        ),
    ]
