# Generated by Django 3.2.7 on 2021-10-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_skils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='skils',
            field=models.JSONField(null=True),
        ),
    ]
