# Generated by Django 3.2.9 on 2021-11-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_regularclass_enroled'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularclass',
            name='hash',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
