# Generated by Django 3.2.7 on 2021-10-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_skils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desciptions',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
