# Generated by Django 3.2.7 on 2021-10-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_desciptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Questions',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='course',
            name='skils',
            field=models.JSONField(),
        ),
    ]
