# Generated by Django 3.2.9 on 2021-11-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_regularclass_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularclass',
            name='hash',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
