# Generated by Django 3.2.7 on 2021-10-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20211029_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='techer_id',
            new_name='teacher_id',
        ),
        migrations.AlterField(
            model_name='course',
            name='Questions',
            field=models.JSONField(default=dict),
        ),
    ]
