# Generated by Django 3.2.9 on 2021-11-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_text_content_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text_content',
            name='content',
            field=models.JSONField(),
        ),
    ]
