# Generated by Django 3.2.7 on 2021-10-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20211029_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='desciptions',
            new_name='discriptions',
        ),
    ]
