# Generated by Django 3.2.9 on 2021-11-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_text_content_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='weeks',
            name='content',
        ),
    ]
