# Generated by Django 3.2.7 on 2021-10-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_rename_desciptions_course_discriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='completed',
            field=models.IntegerField(default=0),
        ),
    ]
