# Generated by Django 3.2.9 on 2021-11-22 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20211122_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='img_content',
            name='week_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='course.weeks'),
        ),
        migrations.AddField(
            model_name='text_content',
            name='week_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='course.weeks'),
        ),
        migrations.AddField(
            model_name='videos',
            name='week_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='course.weeks'),
        ),
    ]
