# Generated by Django 3.2.9 on 2021-11-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='weeks',
            fields=[
                ('course_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('weeks', models.JSONField()),
                ('content', models.JSONField()),
            ],
        ),
    ]
