# Generated by Django 3.2.9 on 2021-11-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20211122_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeks',
            name='overview',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='weeks',
            name='time',
            field=models.CharField(default='0s', max_length=12),
        ),
    ]
