# Generated by Django 3.2.9 on 2021-11-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_weeks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeks',
            old_name='weeks',
            new_name='week',
        ),
    ]
