# Generated by Django 3.2.9 on 2021-11-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20211122_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='regularclass',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
