# Generated by Django 3.2.9 on 2021-11-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_rename_weeks_weeks_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeks',
            name='content',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='week',
            field=models.JSONField(null=True),
        ),
    ]
