# Generated by Django 3.2.9 on 2021-11-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20211122_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeks',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='weeks',
            name='time',
        ),
    ]
