# Generated by Django 3.2.9 on 2021-12-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20211122_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='contentOrder',
            fields=[
                ('week', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('order', models.JSONField()),
            ],
        ),
    ]
