# Generated by Django 3.2.9 on 2021-11-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20211107_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeks',
            name='content',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='week',
            field=models.JSONField(default=list),
        ),
    ]
