# Generated by Django 3.2.9 on 2021-12-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_contentorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text_content',
            name='week_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
