# Generated by Django 3.2.9 on 2021-11-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20211107_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeks',
            name='week',
            field=models.JSONField(default=[0]),
        ),
    ]
