# Generated by Django 3.2.9 on 2021-12-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_text_content_week_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img_content',
            name='week_id',
        ),
        migrations.RemoveField(
            model_name='text_content',
            name='week_id',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='week_id',
        ),
        migrations.AddField(
            model_name='img_content',
            name='course_id',
            field=models.CharField(default=str, max_length=15),
        ),
        migrations.AddField(
            model_name='text_content',
            name='course_id',
            field=models.CharField(default=str, max_length=15),
        ),
        migrations.AddField(
            model_name='videos',
            name='course_id',
            field=models.CharField(default=str, max_length=15),
        ),
    ]
