# Generated by Django 3.2.9 on 2021-12-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20211205_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('questions', models.JSONField()),
                ('totel_point', models.IntegerField()),
                ('to_pass', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
    ]
