# Generated by Django 3.2.9 on 2021-12-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.JSONField(default=[]),
        ),
    ]
