# Generated by Django 3.2.9 on 2021-12-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_alter_quiz_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.JSONField(default=list),
        ),
    ]
