# Generated by Django 3.2.9 on 2021-11-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usernameConvart',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('new_username', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500, null=True)),
                ('DOB', models.DateField(null=True)),
                ('ac_type', models.BooleanField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
