# Generated by Django 3.2.7 on 2021-09-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usernameConvart',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('new_username', models.CharField(max_length=1000)),
            ],
        ),
    ]
