# Generated by Django 3.2.9 on 2021-11-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contact_quality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usernameConvart',
        ),
    ]
