# Generated by Django 3.2.7 on 2021-09-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
