# Generated by Django 3.2.7 on 2021-09-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subtitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
