# Generated by Django 3.2.7 on 2021-10-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211010_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ex',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fb',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='insta',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ql',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tw',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='web',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='yt',
        ),
    ]
