# Generated by Django 3.2.7 on 2021-10-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210919_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('facebook', models.CharField(max_length=500)),
                ('instagram', models.CharField(max_length=500)),
                ('twitter', models.CharField(max_length=500)),
                ('linked_in', models.CharField(max_length=500)),
                ('youtube', models.CharField(max_length=500)),
                ('github', models.CharField(max_length=500)),
                ('gitlab', models.CharField(max_length=500)),
                ('website', models.CharField(max_length=500)),
            ],
        ),
    ]
