# Generated by Django 3.2.7 on 2021-10-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_tocv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tocv',
            new_name='profesional',
        ),
    ]
