# Generated by Django 3.2.7 on 2021-10-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_rename_tocv_profesional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profesional',
        ),
    ]
