# Generated by Django 3.2.7 on 2021-10-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_delete_profesional'),
    ]

    operations = [
        migrations.CreateModel(
            name='profesional',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('domain', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=255)),
                ('qu', models.CharField(max_length=1000)),
                ('ex', models.CharField(max_length=1000)),
            ],
        ),
    ]
