# Generated by Django 3.2.7 on 2021-10-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_profesional'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profesional',
            new_name='tocv',
        ),
    ]
