# Generated by Django 3.2.7 on 2021-10-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_quality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tocv',
        ),
    ]
