# Generated by Django 3.2.7 on 2021-10-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_delete_tocv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course_content',
        ),
        migrations.DeleteModel(
            name='imageContent',
        ),
        migrations.DeleteModel(
            name='textContent',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
