# Generated by Django 3.2.7 on 2021-10-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_auto_20211020_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('techer_id', models.CharField(max_length=100)),
            ],
        ),
    ]
