# Generated by Django 3.2.7 on 2021-10-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
