# Generated by Django 3.2.7 on 2021-10-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
