# Generated by Django 3.2.7 on 2021-10-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_auto_20211020_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
