# Generated by Django 3.2.7 on 2021-10-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0018_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enroled',
            field=models.IntegerField(default=0),
        ),
    ]
