# Generated by Django 3.2.7 on 2021-10-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0020_alter_course_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
